export const SET_ACCOUNT = "ACCOUNT::SET_ACCOUNT";
export const SET_ERROR = "ACCOUNT::SET_ERROR";

export const CLEAR_ACCOUNT = "ACCOUNT::CLEAR_ACCOUNT";
export const ACCOUNT_PENDING = "ACCOUNT::ACCOUNT_PENDING";

export const ALL_CITIES_PENDING = "ACCOUNT::ALL_CITIES_PENDING";
export const SET_ALL_CITIES = "ACCOUNT::SET_ALL_CITIES";
export const SET_ERROR_ALL_CITIES = "ACCOUNT::SET_ERROR_ALL_CITIES";
