export const SET_ACCOUNT = "ACCOUNT::SET_ACCOUNT";
export const SET_ERROR = "ACCOUNT::SET_ERROR";

export const CLEAR_ACCOUNT = "ACCOUNT::CLEAR_ACCOUNT";
export const ACCOUNT_PENDING = "ACCOUNT::ACCOUNT_PENDING";
