export const SET_SEARCH_RESULT = "SEARCH::SET_SEARCH_RESULT";
export const SET_SEARCH_ERROR = "SEARCH::SET_SEARCH_ERROR";

export const SET_CITIES = "SEARCH::SET_CITIES";
export const SET_CITIES_ERROR = "SEARCH::SET_CITIES_ERROR";

export const SEARCH_RESULT_PENDING = "SEARCH::SEARCH_RESULT_PENDING";
export const CITIES_PENDING = "SEARCH::CITIES_PENDING";
